<a href="https://colab.research.google.com/github/GaurangKtype/AER850-Fall23-MyCode/blob/main/tutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a.shape)
print (a)

for elements in a:
    for element in elements:
        print(element)


(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12
